### ISSUE TITLE
Error while executing

### ISSUE THREAD

**Issue by Arunpoochelvan** [Shahabks/myprosody#1]
---------------------------------------------------------------------------
PraatError                                Traceback (most recent call last)
<ipython-input-10-e0c196419dff> in <module>
----> 1 mysp.myspgend(p,c)

c:\users\apoochelvan\audio\lib\site-packages\myprosody\__init__.py in myspgend(m, p)
    245     sourcerun=p+"/"+"dataset"+"/"+"essen"+"/"+"myspsolution.praat"
    246     path=p+"/"+"dataset"+"/"+"audioFiles"+"/"
--> 247     objects= run_file(sourcerun, -20, 2, 0.3, "yes",sound,path, 80, 400, 0.01, capture_output=True)
    248     print (objects[0]) # This will print the info from the sound object, and objects[0] is a parselmouth.Sound object
    249     z1=str( objects[1]) # This will print the info from the textgrid object, and objects[1] is a parselmouth.Data object with a TextGrid inside

PraatError: Unknown variable:
« (ln(f_one
Script line 295 not performed or completed:
Â« lnf0 = (ln(f_one)-5.65)/0.31 Â»
Script not completed.

**Comment by Shahabks** [comment]
I think you need to train the model on your own machine. 
I will have uploaded a repository by Feb 9 here, be called " myMLalgo". Please use that algorithm/program and train your machine locally, save the models (i will write about it there)......It will work

**Comment by Shahabks** [comment]
@Arunpoochelvan 
I revised the script, please download the new version of myprosody.
However, the error you ran into must do with "Voice not recognized" or "the sound of the audio was not clear"

Please try again and let me know your experience
