### ISSUE TITLE
example audio doesnt work or is missing

### ISSUE THREAD

**Issue by welch** [Shahabks/myprosody#12]
**Describe the bug**

`EXAMPLE.pdf` refers to a "Walker" audio file, but this is not present in the project.
There is an audio file "suun3.wav" in `myprosody/myprosody/dataset/audioFiles/`, the directory expected by `myspgend(...)` and other demo functions called in `testpro.py`.
Running `testpro.py` with this path produces many errors saying 
`Try again the sound of the audio was not clear`, and the final result printout lists the 
25% percentile for every category. Is this expected?

This is python 3.6.3 on MacOSX 10.14.5

**Comment by ngc2392** [comment]
I can't get "suun3.wav" to run either. Have you had lucky with any other audio files?

**Comment by welch** [comment]
i eventually gave up on this code base, too messy to pass audio to it without  keeping the directory structure, and wasn't happy with the predictions when I did.

the `parselmouth` module delivered much of what I needed,
and a script at `https://osf.io/6dwr3/` gave me speaking rate estimates.

**Comment by ngc2392** [comment]
I have come across the parselmouth module but didn't look too much into it. Are you able to get the same metrics using that module that this library is suppose to provide? I much rather use a python library that is as close to the actual Praat software as possible, and it seems like parselmouth is exactly that. Right now, I'm mostly interested in metrics such as articulation rate, speech rate, number of pauses, etc.

**Comment by Shahabks** [comment]
## NOTE:
    1- 1- Both My-Voice-Analysis and Myprosody work on Python 3.7 
    2- If you install My-Voice-Analysis through PyPi, please use: 
          mysp=__import__("my-voice-analysis") instead of import myspsolution as mysp
    3- It it better to keep the folder names as single entities for instance "Name_Folder" or "NameFolder" without space in the dirctoy path
