### ISSUE TITLE
Try again audio was not clear #issue

### ISSUE THREAD

**Issue by ahalyaj** [Shahabks/myprosody#13]
I too had the same issue regarding my audio file. And I constantly get this message("Try again the sound of the audio was not clear") after testing every functions (for eg: mysp.myspsr(p,c)). Can you explain the reason why I get this issue even though the audio is in wav format and not of short duration? Can you please check my audio file, and tell if it works for you?

[my-voice-analysis.zip](https://github.com/Shahabks/myprosody/files/4769082/my-voice-analysis.zip)

_Originally posted by @ahalyaj in https://github.com/Shahabks/myprosody/issues/8#issuecomment-643089648_

**Comment by satishluintel** [comment]
same issue here.

**Comment by Shahabks** [comment]
## NOTE:
    1- 1- Both My-Voice-Analysis and Myprosody work on Python 3.7 
    2- If you install My-Voice-Analysis through PyPi, please use: 
          mysp=__import__("my-voice-analysis") instead of import myspsolution as mysp
    3- It it better to keep the folder names as single entities for instance "Name_Folder" or "NameFolder" without space in the dirctoy path

**Comment by durgadp** [comment]
mysp =__import__("myprosody")
import pickle

file_name="suun3.wav" # Audio File title
files_directory=r"/myprosody/dataset/audioFiles" # Path to the Audio_File directory (Python 3.7)
print(file_name)
print(files_directory)
result = mysp.mysptotal(file_name,files_directory)

Same issue while using your folder structure.

**Comment by moj-a** [comment]
Anybody could fix it? I have the same issue.

**Comment by j-j-kam** [comment]
Same issue here. Any solutions yet? Will you update with respect to python 3.9?

**Comment by lk00001** [comment]
Same issue here :( any luck?

**Comment by paul0warren** [comment]
I ran in to this issue, was able to fix it by not including the .wav extension in the file name.  The code adds the extension itself with this line internally:
sound=p+"/"+m".wav"
Where p is the path and m is file name (minus extension).  Also be sure to include the myspsolution.praat file in the path folder or you'll likely see the same error.  If you are still stuck try amending your local copy of the library file to print out the exception.  Right now any exception that occurs during the load will result in "Try again the sound of the audio was not clear"
