### ISSUE TITLE
"Try again the sound of the audio was not clear"

### ISSUE THREAD

**Issue by zliverpool** [Shahabks/myprosody#14]
**Describe the bug**
Keep getting this error using my own audio files (all longer than 20s and sound clear to me) or even the sample file suun3.  I also have following files in my "Test" directory.
1.	myspsolution.praat 
2.	MLTRNL.praat 
3.	stats.csv 

**To Reproduce**
import myprosody as mysp
import pickle

p="suun3" # Audio File title
c="/content/drive/My Drive/Audio/Test" # Path to the Audio_File directory (Python 3.7)
mysp.myspgend(p,c)

Please help. Thanks!

**Comment by Shahabks** [comment]
## NOTE:
    1- 1- Both My-Voice-Analysis and Myprosody work on Python 3.7 
    2- If you install My-Voice-Analysis through PyPi, please use: 
          mysp=__import__("my-voice-analysis") instead of import myspsolution as mysp
    3- It it better to keep the folder names as single entities for instance "Name_Folder" or "NameFolder" without space in the dirctoy path
