### ISSUE TITLE
Models throw error when used with .predict

### ISSUE THREAD

**Issue by ma7555** [Shahabks/myprosody#15]
KNN and SVC models are not working, other models .predict returns a symbol 'c', not sure what is it exactly.

I also want to ask how was these models trained?

**Comment by Shahabks** [comment]
to get KNN and SVC work on a local machine, you need to train the models on your machine (apparently the pre-trained models won't work on other machines) ...... Symbol "C" refers to one of the spoken language proficiency level

**Comment by ma7555** [comment]
can you explain how was these models trained? which dataset was used?

**Comment by Shahabks** [comment]
the original algorithm was developed for a client who provided us with 9000+ audio files of non-native English speakers (from the archive of its students who being prepared for exams over a few years).
We used those audio files + their associated human-rater scores to train the models

**Comment by ma7555** [comment]
understoond, thanks

**Comment by shalabhsingh** [comment]
What are the different spoken language proficiency levels, from good level to bad level?
