### ISSUE TITLE
Percentile Calculation error and calculation logic of parameters

### ISSUE THREAD

**Issue by shalabhsingh** [Shahabks/myprosody#17]
While running of the function `mysp.myprosody(p,c)` in the script `testpro.py`, I started getting multiple doubts which I will request you to clarify. I saw that the function definiton is in myprosody.py and I have doubt in this section of code-

```
for i in range(25):
            sl0=dataframe[4:7:1,i+1]
            score = array[0,i]
            he=scipy.stats.percentileofscore(sl0, score, kind='strict')
            if he==0:
                he=25
                dfout = "%s:\t %f (%s)" %  (nsns[i],he,"% percentile ")
                print(dfout)
            elif he>=25 and he<=75:
                dfout = "%s:\t %f (%s)" % (nsns[i],he,"% percentile ")
                print(dfout)
            else:
                dfout = "%s:\t (%s)" % (nsns[i],":Out of Range")
                print(dfout)
```

Here you are taking percentile for each parameter, from ```stats.csv``` and reporting percentile using "strict" scoring. As a result percentiles can only be 0, 25, 33.3, 66.6 or out of range. What is the reasoning behind using fixed percentile values? Also if we also have min and max values (0 and 100 percentiles respectively), then why we are reporting some >75 percentiles as out of range?

Apart from this, I want to know the definition and calculating procedure for some of the features-
* What is ```No._long_pause``` (confused as I didn't expect it to be in decimals)
* What is ```formants_index``` ?
* While giving percentile for parameters like ```No._detected_vowel```, is the time of speech considered (it doesn't make without that right) ?
* How is intonation index, TOEFL score and Shannon index calculated here? Can you explain briefly? I see it's done in the praat file but how?

Also, what are the accuracies of the models used to calculate these scores? Is this documented in some paper or report?

**Comment by Shahabks** [comment]
These articles might be of interest to you 
"Automatic scoring of non-native spontaneous speech in tests of spoken English", Speech Communication, Volume 51, Issue 10, October 2009, Pages 883-895
"A three-stage approach to the automated scoring of spontaneous spoken responses", Computer Speech & Language, Volume 25, Issue 2, April 2011, Pages 282-306
"Automated Scoring of Nonnative Speech Using the SpeechRaterSM v. 5.0 Engine", ETS research report, Volume 2018, Issue 1, December 2018, Pages: 1-28
