### ISSUE TITLE
viseme generation

### ISSUE THREAD

**Issue by AhmadManzoor** [Shahabks/myprosody#18]
hi @Shahabks thank you for sharing  your work. I am trying to generate viseme from audio such as 

> AAA', 'Eh', 'AHH', 'OHH', 'UUU', 'IEE', 'RRR', 'WWW', 'SSS', 'FFF', 'TTH', 'MBP', 'SSH', 'Schwa', 'GK', 'LNTD

can you please guide me how can achieve this. and in what direction i should look into it. maybe you can share some related work which i can extend. i will really appreciate your help.

**Comment by Shahabks** [comment]
Thanks ..... Indeed an interesting topic, though I have never done
