### ISSUE TITLE
please explain the meaning of Language Level Estimator and add it to the example.pdf

### ISSUE THREAD

**Issue by InnovativeCoder** [Shahabks/myprosody#3]
please explain the meaning of Language Level Estimator and add it to the example.pdf

**Comment by Shahabks** [comment]
It measures the spoken language proficiency level by analyzing some features such as prosody, pronunciation, structures and plug-in them into a defined rubric  .....to see more details please see  https://shahabks.github.io/Speech-Rater/    and    https://github.com/Shahabks/Speech-Rater
