### ISSUE TITLE
Fillers

### ISSUE THREAD

**Issue by antoninklopp** [Shahabks/myprosody#6]
Hi, 

I am looking for filler words and filled pauses, like it seems to be mentioned in the documentation. However, when I run the script, I have the impression that the fillers are actually the moments where people speak. 

Here is a simple view of the outputed textgrid

> class = "IntervalTier" 
        name = "silences" 
        xmin = 0 
        xmax = 257.9040362811791 
        intervals: size = 82 
        intervals [1]:
            xmin = 0 
            xmax = 21.536018140589544 
            text = "sounding" 
        intervals [2]:
            xmin = 21.536018140589544 
            xmax = 22.048018140589544 
            text = "silent" 
        intervals [3]:
            xmin = 22.048018140589544 
            xmax = 30.320018140589543 
            text = "sounding" 
        intervals [4]:
            xmin = 30.320018140589543 
            xmax = 30.672018140589543 
            text = "silent" 

Am I not understanding something? 

Thanks for your help!

**Comment by Shahabks** [comment]
Filler words are captured based on the quality and quantity of CV intervals. Your impression for the latter one is right if you mean by "when people speak", silence pulse between syllables
