### ISSUE TITLE
No module named parselmouth.praat

### ISSUE THREAD

**Issue by rohitsinha0807** [Shahabks/myprosody#9]
Hey I tried installing both parselmouth and praat-parselmouth==0.3.3 but I am getting the error "No module named parselmouth.praat" 

Please suggest how to install this module.

Awaiting reply kindoff urgent

**Comment by tudou2015** [comment]
pip install praat-parselmouth
you can found here: https://parselmouth.readthedocs.io/en/stable/installation.html
